export const dataCards = [
  {
    id: 1,
    category: ['приключения', 'боевик', 'комедия', 'драма', 'фэнтези'],
    name: 'Боруто',
    avatar: 'https://gen.jut.su/templates/school/images/anime_naruto_season-3.jpg',
    url: 'https://jut.su/naruto/season-3/',
  },
  {
    id: 2,
    category: ['мистика', 'детектив', 'триллер', 'психология'],
    name: 'Тетрадь смерти',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_death-note.jpg',
    url: 'https://jut.su/death-note/',
  },
  {
    id: 3,
    category: ['приключения', 'боевик', 'драма', 'фэнтези', 'триллер'],
    name: 'Атака титанов',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_shingeki-no-kyojin.jpg',
    url: 'https://jut.su/shingeki-no-kyojin/',
  },
  {
    id: 4,
    category: ['боевик', 'комедия', 'повседневность', 'фантастика'],
    name: 'Ван панч мен',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_one-punch-man.jpg',
    url: 'https://jut.su/one-punch-man/',
  },
  {
    id: 5,
    category: ['боевик', 'драма', 'фантастика', 'триллер'],
    name: 'Токийский гуль',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_tokyo-ghoul.jpg',
    url: 'https://jut.su/tokyo-ghoul/',
  },
  {
    id: 6,
    category: ['приключения', 'боевик', 'драма', 'фантастика'],
    name: 'Стальной алхимик',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_fullmetal-alchemist.jpg',
    url: 'https://jut.su/fullmetal-alchemist/',
  },
  {
    id: 7,
    category: ['приключения', 'боевик', 'фантастика'],
    name: 'Моя геройская академия',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_boku-no-hero-academia.jpg',
    url: 'https://jut.su/boku-no-hero-academia/',
  },
  {
    id: 8,
    category: ['приключения', 'боевик', 'драма', 'фэнтези', 'триллер'],
    name: 'Хантер х Хантер',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_hunter-x-hunter.jpg',
    url: 'https://jut.su/hunter-x-hunter/',
  },
  {
    id: 9,
    category: ['приключения', 'боевик', 'комедия', 'драма', 'фэнтези'],
    name: 'Ван пис',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_onepiece.jpg',
    url: 'https://jut.su/onepiece/',
  },
  {
    id: 10,
    category: ['приключения', 'боевик', 'комедия', 'драма', 'фэнтези'],
    name: 'Блич',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_bleach.jpg',
    url: 'https://jut.su/bleach/',
  },
  {
    id: 11,
    category: ['приключения', 'боевик', 'комедия', 'драма', 'фантастика'],
    name: 'Класс убийц',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_ansatsu-kyoushitsu.jpg',
    url: 'https://jut.su/ansatsu-kyoushitsu/',
  },
  {
    id: 12,
    category: ['мистика', 'боевик', 'комедия', 'драма', 'фантастика'],
    name: 'Моб психо 100',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_mob-psycho-100.jpg',
    url: 'https://jut.su/mob-psycho-100/',
  },
  {
    id: 13,
    category: ['фэнтези', 'боевик', 'мистика'],
    name: 'Клинок рассекающий демонов',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_kimetsu-no-yaiba.jpg',
    url: 'https://jut.su/kimetsu-no-yaiba/',
  },
  {
    id: 14,
    category: ['фантастика', 'детектив', 'триллер'],
    name: 'Обещанный новерленд',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_yakusoku-neverland.jpg',
    url: 'https://jut.su/yakusoku-neverland/',
  },
  {
    id: 15,
    category: ['приключения', 'фантастика'],
    name: 'Доктор Стоун',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_dr-stone.jpg',
    url: 'https://jut.su/dr-stone/',
  },
  {
    id: 16,
    category: ['романтика', 'психология', 'комедия'],
    name: 'Кагуя сама',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_kaguya-sama.jpg',
    url: 'https://jut.su/kaguya-sama/',
  },
  {
    id: 17,
    category: ['приключения', 'комедия', 'драма'],
    name: 'Баскетбол Куроко',
    avatar: 'https://gen.jut.su/uploads/animethumbs/anime_kuroko-no-basuke.jpg',
    url: 'https://jut.su/kuroko-no-basuke/',
  },
]
